spring:
  application:
    name: catalog-service
  config:
    import:
    - "optional:configserver:"
  cloud:
    config:
      uri:
      - http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  datasource:
    username: "root"
    password: ""
    url: "jdbc:mysql://localhost:3306/productdb_catalog?serverTimezone=UTC&useSSL=false"
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  flyway:
    url: dbc:mysql://localhost:3306/productdb_catalog?serverTimezone=UTC&useSSL=false"
    user: root
    password: 
    locations:
    - classpath:db/migration
    enabled: true
server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 20
      min-spare: 5 
management:
  endpoints:
    web:
      exposure:
        include: refresh
  
polar:
  greeting: Welcome to the local book catalog!
