version: "3.3"
services:
  catalog-service:
    depends_on:
      - polar-mysql
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
      - "8001:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:mysql://polar-mysql:3306/productdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata

  polar-mysql:
    image: "mysql:8.0.29"
    container_name: "polar-mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=productdb_catalog
